version: 2.1

#####################
####### Orbs ########
#####################
orbs:
  # Currently, docker orb is used to build the docker image and not publish it,
  # Therefore the user and password environment variables does not need to be set.
  docker-orb: circleci/docker@0.5.1

#####################
##### Executors #####
#####################
executors:
  # Used for running one-time docker images.
  # Currnet image (201808-01) runs docker 18.06.0-ce and docker-compose 1.22.0.
  # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
  machine-docker:
    machine:
      image: "circleci/classic:201808-01"
    working_directory: ~/workspace

  # Used for executing npm modules.
  node-docker:
    docker:
      - image: "circleci/node:lts"
    working_directory: ~/workspace

  # Used for starting python programs.
  python-docker:
    docker:
      - image: "circleci/python:3.7.3-stretch"
    working_directory: ~/workspace
    environment:
      TZ: "Asia/Jerusalem"

#####################
##### Commands ######
#####################
commands:
  ##################################################################
  ### Commands for creating environments and save/restore caches ###
  ##################################################################

  # Docker images are pulled here and saved to cache.
  # Use with the machine-docker executer as preparation before running one-time docker containers.
  prepare-machine:
    description: Prepare the virtual machine
    steps:
      - restore_cache:
          keys:
            - v1-switcher-webapi-machine-{{ .Branch }}-{{ checksum "Dockerfile" }}-{{ checksum ".dockerignore" }}
      - run:
          name: Download docker images and save to cache
          command: |
            filename=docker-cache/saved_images.tar
            if [[ -f "$filename" ]]; then docker load < "$filename"; fi
            mkdir -p docker-cache
            docker pull hadolint/hadolint:v1.16.3
            docker pull koalaman/shellcheck:v0.6.0
            docker save -o "$filename" hadolint/hadolint:v1.16.3 koalaman/shellcheck:v0.6.0

      - save_cache:
          key: v1-switcher-webapi-machine-{{ .Branch }}-{{ checksum "Dockerfile" }}-{{ checksum ".dockerignore" }}
          paths:
            - docker-cache

  # Node packages are installed here and then saved to cache.
  # Use with the node-docker executer as preparation before executing npm modules.
  prepare-node:
    description: Prepare node environment
    steps:
      - restore_cache:
          keys:
            - v1-switcher-webapi-node-{{ .Branch }}-{{ checksum ".prettierignore" }}-{{ checksum ".prettierrc.yml" }}
      - run:
          name: Install prettier
          command: npm install prettier@1.18.2
      - save_cache:
          key: v1-switcher-webapi-node-{{ .Branch }}-{{ checksum ".prettierignore" }}-{{ checksum ".prettierrc.yml" }}
          paths:
            - ./node_modules

  # Pypi packages are installed here into a venv that is saved to cache.
  # Use with the python-docker executer as preparaton before starting python programs.
  prepare-python:
    description: Prepare python's virtual environment
    steps:
      - restore_cache:
          keys:
            - v1-switcher-webapi-python-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}
      - run:
          name: Create the venv, install all requirements and save to cache
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -q --progress-bar off -r requirements.txt -c requirements_constraints.txt
            pip install -q --progress-bar off -r requirements_test.txt -c requirements_constraints.txt
            pip install -q --progress-bar off -r requirements_docs.txt -c requirements_constraints.txt
      - save_cache:
          key: v1-switcher-webapi-python-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_test.txt" }}
          paths:
            - ./venv

  ######################################################################################################
  ### Commands running inside the machine-docker executer after running  the prepare-machine command ###
  ######################################################################################################
  hadolint-docker:
    description: Run one-time container for hadolint linter against Dockerfile
    steps:
      - run:
          name: Run hadolint docker
          command: docker run --rm -i hadolint/hadolint:v1.16.3 < Dockerfile

  shellcheck-docker:
    description: Run one-time container for shellcheck linter against shellscripts/*.sh
    steps:
      - run:
          name: Run shellcheck docker
          command: docker run --rm -v "$PWD/shellscripts/:/mnt/" koalaman/shellcheck:v0.6.0 $(ls -A1 shellscripts)

  ######################################################################################################
  ###### Commands running inside the node-docker executer after running the prepare-node command #######
  ######################################################################################################
  run-prettier:
    description: Execute npm's prettier module to linting yaml and md files
    steps:
      - run:
          name: Prettier
          command: node_modules/prettier/bin-prettier.js --config .prettierrc.yml --ignore-path .prettierignore --check *.* **/*.*

  ######################################################################################################
  #### Commands running inside the python-docker executer after running the prepare-python command #####
  ######################################################################################################
  run-docs-linters:
    description: Run python doc8 linter against docs/source/*.rst
    steps:
      - run:
          name: Doc8
          command: |
            . venv/bin/activate
            doc8 --config doc8.ini docs/source

  sphinx-build:
    description: Verify build docs with python sphinx by building into temp directory
    steps:
      - run:
          name: Sphinx-build
          command: |
            . venv/bin/activate
            mkdir sphinxtemp
            sphinx-build -W -b html -d sphinxtemp/doctrees docs/source sphinxtemp/html
            rm -r sphinxtemp

  check-security:
    description: Run python bandit against py files
    steps:
      - run:
          name: Code-security
          command: |
            . venv/bin/activate
            bandit -rvc bandit.yml pyscripts docs/source/conf.py -l -ii

  run-code-linters:
    description: Run python flake8 and pylint againt py files
    steps:
      - run:
          name: Linters
          command: |
            . venv/bin/activate
            flake8 --statistics --count --doctests --verbose pyscripts/ docs/source/
            pylint --disable fixme --rcfile pylintrc pyscripts/ docs/source/conf.py

  run-mypy:
    description: Run mypy type-checking againt py files
    steps:
      - run:
          name: Mypy
          command: |
            . venv/bin/activate
            mypy --config-file mypy.ini pyscripts/ docs/source/conf.py

  run-tests-with-coverage:
    description: Run pytest test cases with coverage report against py files
    steps:
      - run:
          name: Pytest
          command: |
            . venv/bin/activate
            pytest -vs --cov --cov-config=.coveragerc --cov-report=xml:coverage_report/coverage.xml pyscripts/test_server.py
      - persist_to_workspace:
          root: coverage_report/
          paths:
            - coverage.xml
      - store_artifacts:
          path: coverage_report
      - store_test_results:
          path: coverage_report

#####################
####### Jobs ########
#####################
jobs:
  #############################################
  ### Jobs for the docs-lint-build workflow ###
  #############################################
  docs-linters-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - run-docs-linters

  sphinx-build-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - sphinx-build

  #############################################
  ### Jobs for the code-lint-test workflow ####
  #############################################
  prettier-job:
    executor:
      name: node-docker
    steps:
      - checkout
      - prepare-node
      - run-prettier

  shellcheck-docker-job:
    executor:
      name: machine-docker
    steps:
      - checkout
      - prepare-machine
      - shellcheck-docker

  hadolint-docker-job:
    executor:
      name: machine-docker
    steps:
      - checkout
      - prepare-machine
      - hadolint-docker

  docker-check-and-build-job:
    executor:
      name: machine-docker
    steps:
      - checkout
      - docker-orb/build:
          dockerfile: Dockerfile
          path: .
          image: tomerfi/switcher_webapi
          tag: testing
          extra_build_args: '--build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VCS_REF=fakeref --build-arg VERSION=testing'

  security-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - check-security

  code-linters-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - run-code-linters

  mypy-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - run-mypy

  unittests-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - run-tests-with-coverage

  coverage-reports-job:
    executor:
      name: python-docker
    steps:
      - checkout
      - prepare-python
      - attach_workspace:
          at: coverage_report/
      - run:
          name: CodeCov
          command: |
            . venv/bin/activate
            codecov --file coverage_report/coverage.xml
            python-codacy-coverage -r coverage_report/coverage.xml

#####################
##### Workslows #####
#####################
workflows:
  version: "2"

  # Lint and build the documantation site files
  docs-lint-build:
    jobs:
      - docs-linters-job

      - sphinx-build-job:
          requires:
            - docs-linters-job

  # Lint and the test the code, scripts and Dockerfile
  code-lint-test:
    jobs:
      - prettier-job

      - shellcheck-docker-job

      - hadolint-docker-job:
          requires:
            - prettier-job
            - shellcheck-docker-job

      - docker-check-and-build-job:
          requires:
            - hadolint-docker-job

      - security-job:
          requires:
            - docker-check-and-build-job

      - code-linters-job:
          requires:
            - docker-check-and-build-job

      - mypy-job:
          requires:
            - docker-check-and-build-job

      - unittests-job:
          requires:
            - security-job
            - code-linters-job
            - mypy-job

      - coverage-reports-job:
          requires:
            - unittests-job
