---
name: PullRequestsUtils

on: pull_request

jobs:
  wip-to-pending:
    runs-on: ubuntu-latest
    name: Set WIP labeled PRs as pending
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set WIP PR status to pending
        uses: wip/action@v1.0.0
