---
name: ShellTest

on:
  pull_request:
    branch: dev

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify shell scripts
    steps:
      - name: Source checkout
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          level: error
          path: shellscripts
